version: "3"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - redis

  worker:
    image: anroots/webmon
    build:
      context: .
    command:
      - 'python'
      - 'worker.py'
      - "--rhost=redis"
    depends_on:
      - redis
    environment:
      - FLEEP_HOOK=
    networks:
      - redis

  certstream:
    image: anroots/webmon
    build:
      context: .
    command:
      - "python"
      - "main.py"
      - "--rhost=redis"
      - "--tld=ee"
      - "--tld=com"
    networks:
      - redis

    depends_on:
      - redis

networks:
  redis: