version: "3"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    network_mode: host

  worker:
    image: anroots/webmon
    build:
      context: .
    command:
      - 'rq'
      - 'worker'
      - "-u 'redis://redis'"
    depends_on:
      - redis
    network_mode: host
    environment:
      - FLEEP_HOOK=

  certstream:
    image: anroots/webmon
    build:
      context: .
    command:
      - "python"
      - "main.py"
      - "--rhost=localhost"
      - "--tld=ee"
      - "--tld=com"
    network_mode: host

    depends_on:
      - redis

