<?php

return [

    'scanners' => [
        'git' => [
            'class' => \App\Jobs\ScanPublicGitFolder::class,
            'min_scan_interval'=> 5000 // ~3 days
        ],
        'unresolvable' => [
            'class' => \App\Jobs\CheckDomainResolves::class,
            'min_scan_interval' => 10080 // 1 week
        ],
        'wordlist' => [
            'class' => \App\Jobs\ScanWordList::class,
            'min_scan_interval'=> 5000, // ~3 days

            // Delay in milliseconds between each request
            // In order to not DOS the service
            'request_delay' => 200,
            'wordlist' => [
                '/.bash_history',
                '/.config',
                '/.config.php.swp',
                '/.configuration.php.swp',
                '/.env',
                '/.environment',
                '/.error_log',
                '/.history',
                '/.htpasswd',
                '/.idea/workspace.xml',
                '/.npmrc',
                '/.passwd',
                '/.psql_history',
                '/.mysql_history',
                '/.sh_history',
                '/.ssh/id_rsa',
                '/.ssh/know_hosts',
                '/access.log',
                '/access_log',
                '/app/config/database.yml',
                '/app/log/',
                '/app/logs/',
                '/backup.rar',
                '/backup.sql',
                '/backup.tar',
                '/backup.tar.gz',
                '/backup.tgz',
                '/backup.zip',
                '/backup/',
                '/backups/',
                '/conf/',
                '/conf/server.xml',
                '/config.bak',
                '/config.inc',
                '/config.inc.bak',
                '/config.inc.old',
                '/config.inc.txt',
                '/config.inc~',
                '/config.ini',
                '/config.json',
                '/config.save',
                '/config.swp',
                '/config.yml',
                '/Config/',
                '/config/',
                '/config/database.yml',
                '/configuration.ini',
                '/configuration.php.old',
                '/configuration.php.save',
                '/configuration.php~',
                '/data/logs/',
                '/database.sql',
                '/database.sqlite',
                '/database.txt',
                '/database.yml',
                '/db.csv',
                '/db.inc',
                '/db.ini',
                '/db.log',
                '/db.properties',
                '/db.sql',
                '/db.sqlite',
                '/debug/',
                '/dump.sql',
                '/dump.tar',
                '/dump.tar.gz',
                '/dump.tgz',
                '/dump.zip',
                '/error',
                '/error-log',
                '/error-log.txt',
                '/error.log',
                '/error_log',
                '/files/',
                '/htpasswd',
                '/index.php~',
                '/install/',
                '/localhost.sql',
                '/localhost.tar',
                '/localhost.tar.gz',
                '/localhost.tgz',
                '/log.txt',
                '/log/',
                '/log/access.log',
                '/log/access_log',
                '/log/error.log',
                '/log/error_log',
                '/logs/',
                '/logs/access.log',
                '/logs/access_log',
                '/logs/error.log',
                '/logs/error_log',
                '/mysql.err',
                '/mysql.log',
                '/mysql.sql',
                '/nano.save',
                '/php.ini',
                '/php.ini~',
                '/settings.bak',
                '/settings.ini',
                '/settings.php.bak',
                '/sql.sql',
                '/sql.tar',
                '/sql.tgz',
                '/sql.txt',
                '/tmp/',
                '/web-console/',
                '/WEB-INF./web.xml',
                '/WEB-INF/config.xml',
                '/WEB-INF/web.xml',
                '/web.config',
                '/wp-config.bak',
                '/wp-config.old',
                '/wp-config.php.bak',
                '/wp-config.php~',
                '/apache/logs/access.log ',
                '/apache/logs/error.log ',
                '/httpd/logs/access.log ',
                '/httpd/logs/error.log ',
                '/logs/access.log ',
                '/logs/error.log ',
                '/phpmyadmin',
                '/data/',
                '/env',
                '/Dockerfile',
                '/db_backup.sql',
                '/db_backup.sql.tar',
                '/db_backup.tar.gz',
                '/db_backup.tar',
                '/dump.sql',
                '/db_backup.sql.zip',
                '/db_backup.sql.tar.gzip',
                '/db_backup.zip',
                '/db_backup.tgz',
                '/db_backup.sql.gz',
                '/db_backup.sql.tar.gz',
                '/db_backup.gz',
                '/db_backup.sql.sql',
                '/sql.tar.gzip',
                '/sql.sql.tgz',
                '/sql.tar.gz',
                '/sql.zip',
                '/dump.tgz',
                '/sql.tgz',
                '/sql.tar',
                '/sql.sql',
                '/db_backup.sql.tgz',
                '/sql.gz',
                '/db_backup.tar.gzip',
                '/mysql.sql',
                '/sql.sql.tar.gz',
                '/mysql.tar.gzip',
                '/sql.sql.zip',
                '/mysql.gz',
                '/mysql.sql.tar',
                '/mysql.tgz',
                '/mysql.tar.gz',
                '/www.sql.sql',
                '/www.sql.tgz',
                '/dbdump.tar.gz',
                '/mysql.tar',
                '/dump.sql.tar.gz',
                '/backup.sql.gz',
                '/sql.sql.tar',
                '/sql.sql.gz',
                '/mysql.sql.tar.gzip',
                '/dbdump.sql.tar',
                '/backup.sql.zip',
                '/dump.tar.gz',
                '/dbdump.zip',
                '/backup.sql.sql',
                '/dump.sql.gz',
                '/backup.sql.tar.gz',
                '/sql.sql.tar.gzip',
                '/dbdump.sql.tgz',
                '/dbdump.sql.tar.gz',
                '/dbdump.sql.gz',
                '/dump.tar',
                '/dbdump.sql.tar.gzip',
                '/mysql.sql.tar.gz',
                '/1.sql.zip',
                '/mysql.zip',
                '/dump.gz',
                '/dbdump.sql.zip',
                '/backup.sql.tgz',
                '/dump.sql.tar',
                '/dbdump.tgz',
                '/dump.sql.zip',
                '/db.sql.tgz',
                '/db.tar.gz',
                '/data.sql.sql',
                '/db.sql.zip',
                '/www.sql',
                '/backup.sql.tar.gzip',
                '/dump.sql.tgz',
                '/backup.sql.tar',
                '/mysql.sql.gz',
                '/mysql.sql.zip',
                '/upload.sql',
                '/temp.sql.tar',
                '/users.sql',
                '/upload.sql.tar.gz',
                '/home.sql',
                '/www.sql.tar',
                '/data.sql.tar.gzip',
                '/web.sql.tar.gzip',
                '/temp.sql.gz',
                '/dbdump.sql',
                '/users.sql.tar',
                '/db.tar.gzip',
                '/db.sql.sql',
                '/dbdump.tar.gzip',
                '/users.sql.tar.gzip',
                '/temp.sql.tar.gzip',
                '/db.sql',
                '/users.sql.gz',
                '/web.sql.tgz',
                '/dump.sql.tar.gzip',
                '/db.gz',
                '/db.tar',
                '/db.sql.tar.gz',
                '/upload.sql.gz',
                '/home.sql.tar.gz',
                '/db.zip',
                '/home.sql.tgz',
                '/web.sql.tar.gz',
                '/users.sql.zip',
                '/data.sql',
                '/upload.sql.tar',
                '/site.sql.tar.gzip',
                '/backup.sql',
                '/web.sql.zip',
                '/data.sql.tar',
                '/data.sql.tgz',
                '/temp.sql.tgz',
                '/www.sql.tar.gz',
                '/db.tgz',
                '/dbdump.sql.sql',
                '/db.sql.gz',
                '/site.sql',
                '/dbadmin.gz',
                '/db.sql.tar',
                '/users.gz',
                '/dbadmin.tgz',
                '/www.sql.gz',
                '/dbadmin.tar.gz',
                '/users.tar.gzip',
                '/home.sql.zip',
                '/dbadmin.sql.tar',
                '/site.sql.tar.gz',
                '/mysql.sql.tgz',
                '/temp.sql.tar.gz',
                '/home.sql.sql',
                '/dump.zip',
                '/dbadmin.sql.gz',
                '/dbadmin.tar',
                '/db.sql.tar.gzip',
                '/www.sql.zip',
                '/dbadmin.sql',
                '/home.sql.tar',
                '/data.sql.tar.gz',
                '/dump.tar.gzip',
                '/dbdump.gz',
                '/temp.sql',
                '/web.sql',
                '/dbadmin.sql.tar.gzip',
                '/dbadmin.sql.zip',
                '/data.sql.zip',
                '/dbadmin.sql.sql',
                '/users.tar',
                '/dbadmin.sql.tgz',
                '/site.sql.gz',
                '/dbadmin.zip',
                '/site.sql.tgz',
                '/dbdump.tar',
                '/data.sql.gz',
                '/site.sql.zip',
                '/www.sql.tar.gzip',
                '/web.sql.gz',
                '/site.sql.tar'
            ]
        ]
    ],

    // Do not run any scanners on domains that have been scanned within this time (in minutes)
    'min_scan_interval' => env('WEBMON_MIN_INTERVAL', 4320), // default 3 days

    // Do not re-notify about scanner findings for the domain, if we have already notified about it within this time (in minutes)
    'min_renotify_interval'=> env('WEBMON_RENOTIFY_INTERVAL', 43800) // 1 month

];
